version: "1"
services:
  app:
    build: .
    container_name: yettel-task-app
    env_file: .env
    volumes:
      - .:/usr/src/app
    ports:
      - "13000:3000"
    depends_on:
      - db
    command: ["npm", "run", "start:migrate"]

  db:
    image: postgres:latest
    container_name: yettel-task-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: yettel_task_db
